### ISSUE TITLE
Internationalise all of the app content and UI elements

### ISSUE THREAD

**Issue by rgoj** [Maptio/maptio#749]
### General
* [X] Welcome screen
* [X] Header
* [X] Footer
* [X] Log in, registration and log out flows (including Auth0 screens)
* [X] Profile page (including team member editing form reused throughout the app)
* [X] Onboarding screens
* [X] Onboarding messages

### Workspace
* [X] Structure editing
* [X] Tag editing
* [X] Circle editing
* [X] Role editing
* [x] Toolbar
  * [X] Icon text
  * [x] Popup windows
* [ ] Circle views
  * [ ] #771
  * [x] RMB click context menu
* [x] Directory view
* [x] Network view
* [x] Template tags

### Other
* [X] Settings pages
* [x] Pricing page
* [x] Breadcrumbs
* [x] All error messages (80% are already done, this task entails searching for the ones that are rare and more difficult to trigger)

### TODO Later
* [ ] People import
  * [ ] Internationalise the word "browse" in the bootstrap file picker or just change the file picker
  * [ ] Currently the app expects the CSV headings to be in English and that is hardcoded (it doesn't need to work this way, we just need a moment of UX thinking and some code changes and testing)
