### ISSUE TITLE
Improve side panels

### ISSUE THREAD

**Issue by rgoj** [Maptio/maptio#848]
Now that we've improved the outliner experience and put in the building blocks necessary for better state management in the workspace, the next big improvement should probably be replacing the side panels. There are many aspects to this task, here are some:

* [X] Initial planning and design work
  * _Completed Mon 13 Nov 2023_
  * Done mostly in spare time - over many months - and catchups, this was never estimated, only the final couple of tasks were ever written out
  * [X] Collating design ideas so far
    * Collated on paper in my notes, can scan and post somewhere if need be!
  * [X] Doing a collaborative design session to explore all the different options we've got
    * By the time we got to discussing this, I was pretty clear on the direction I'd like to take here, so we ended up going through all the ideas so far and agreeing that might be the best best - see paper notes
    
The below plan is crossed out as it went out the window as I started working on this! No plan survives contact with the codebase, as they say, ahem.

* [ ]  ~#847~
  * ~_Time box: 2 days, Actual time taken so far: 0.9 day (Thu 16 Nov - Mon 20 Nov inclusive)_~
  * ~Let's start the wider work on the side panels with a 2 day time box - to clean up the outliner code, clean up the side panel code, see what is and isn't possible~
* ~[ ] Planning and estimation for the entire epic~
  * ~_Estimate: 1-2 days, Actual time taken so far: 0.5 (Mon 20 Nov)_~
  * ~Let's spend 1-2 days on planning the next steps - how do we approach this work?~
  * ~Let's try to plan it in such a way as to avoid disappearing into a very long coding time box before shipping something visible to the users, perhaps it might be possible to ship smaller improvements gradually as we go along?~
* ~[ ] Create a very basic read-only preview of the new side panels at `/preview`~
  * ~_Estimate: 6-8 days_~
* ~[ ] Taking stock and planning and estimation for next steps to use the new preview code in the workspace and make it fully functional~
  * ~_Estimate: 2-3 days_~

**Comment by rgoj** [comment]
Here's what the initial plan looked like after catchup on Monday 20 November - archiving after making edits:

> * [ ] #847
> * [ ] ...the above task ☝🏻 includes planning the next tasks, below are just some initial thoughts
> * [ ] Collating design ideas so far
> * [ ] Doing a collaborative design session to explore all the different options we've got

**Comment by rgoj** [comment]
Rough estimates to get to a shippable to production workspace: 32 days - a rough estimate during catchup and doesn't include changing the navigation panel thoroughly.

**Comment by rgoj** [comment]
The bulk of the work is done for this, but there's still the usual hundreds of tasks I think it'd be best to do before shipping fully... so here's a list for prioritisation.

### Remaining decisions
* [ ] Should we ship to production at `/preview/` first for a while? How do we approach not suddenly forcing a massive change on everyone?
  * What we discussed so far was, roughly: first ship to `/preview/`, let some people know, gather feedback, see what to do next. With a view to perhaps then ship to `/map/` for everyone while also sending out a message / video explaining the change.
* [ ] Should we ship the panels before we remove the header?
  * Yeah, probably yes, let's do that. It's suboptimal, but it works, especially after some small layout amendments have been implemented. The full reworking of the header will take a while as it's design-heavy.
  
### Remaining work
... to be continued

**Comment by tomnixon** [comment]
One small but essential item: When you click edit tags from the right-side panel it needs to open the left panel if it's currently closed otherwise it looks like nothing happened.

And a 'could do' - allow the panels to be resized.

**Comment by tomnixon** [comment]
Now that we've improved the layout, the tags tab is really standing out to me as confusing. Until we get to the next iteration of the design with circles, tags, roles, people all nicely laid out, let's change the text on the tags tab in the left panel to something shorter and more descriptive: "Customise a set of tags here then add them to your circles to map themes, status and more."
Then a link to the tags help video: https://learning.maptio.com/using-tags
The link could say "Learn more", or be an (i) icon or whatever you think works best Romek.

**Comment by rgoj** [comment]
Thanks, Tom, the text changes make perfect sense! Yeah, I agree the tags tab feels even more confusing now! I've added the tasks you mentioned to the list above.
